"""empty message

Revision ID: 6e4643ea8ad6
Revises: 
Create Date: 2020-03-19 14:11:19.827650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4643ea8ad6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('People', sa.Column('bober', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('People', 'bober')
    # ### end Alembic commands ###
